#include "hal_data.h"

FSP_CPP_HEADER
void Segment_Initial_Setting();
void LED_Initial_Setting();
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

uint8_t led_select = 0, stop_key = 0;
int count_number = -1; //시작하면서 count_number++가 실행되므로 -1로 정의
uint8_t fnd_number[10] = {0x03, 0x9F, 0x25, 0x0D, 0x99, 0x49, 0x41, 0x1B, 0x01, 0x09};

bsp_io_port_pin_t fnd_segment_ledindex[7] = {
                                             BSP_IO_PORT_06_PIN_04,
                                             BSP_IO_PORT_06_PIN_05,
                                             BSP_IO_PORT_06_PIN_06,
                                             BSP_IO_PORT_06_PIN_07,
                                             BSP_IO_PORT_06_PIN_11,
                                             BSP_IO_PORT_06_PIN_12,
                                             BSP_IO_PORT_06_PIN_13
};
bsp_io_port_pin_t led_index[4] = {
                                             BSP_IO_PORT_10_PIN_08,
                                             BSP_IO_PORT_10_PIN_09,
                                             BSP_IO_PORT_10_PIN_10,
                                             BSP_IO_PORT_11_PIN_00,
};

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    R_AGT_Open(&g_timer0_ctrl, &g_timer0_cfg);
    R_AGT_Start(&g_timer0_ctrl);

    R_ICU_ExternalIrqOpen(&g_external_irq11_ctrl, &g_external_irq11_cfg);
    R_ICU_ExternalIrqEnable(&g_external_irq11_ctrl);

    Segment_Initial_Setting();
    LED_Initial_Setting();
    while(true)
    {
        if (count_number >= 10)
        {
            LED_Initial_Setting();
            R_AGT_Stop(&g_timer0_ctrl);
            return;
        }
        if (stop_key == 1)
        {
            R_AGT_Stop(&g_timer0_ctrl);
            R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_03_PIN_08, BSP_IO_LEVEL_HIGH);
            for (uint8_t idx = 0; idx < 7; idx++)
            {
                uint8_t key = (uint8_t)(fnd_number[count_number % 10] >> (7 - idx) & 0x01);
                R_IOPORT_PinWrite(&g_ioport_ctrl, fnd_segment_ledindex[idx], key);
            }
        }
        else
        {
            Segment_Initial_Setting();
            R_AGT_Start(&g_timer0_ctrl);
        }
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

void Segment_Initial_Setting()
{
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_03_PIN_05, BSP_IO_LEVEL_LOW);
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_03_PIN_06, BSP_IO_LEVEL_LOW);
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_03_PIN_07, BSP_IO_LEVEL_LOW);
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_03_PIN_08, BSP_IO_LEVEL_LOW);
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_06_PIN_04, BSP_IO_LEVEL_HIGH);
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_06_PIN_05, BSP_IO_LEVEL_HIGH);
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_06_PIN_06, BSP_IO_LEVEL_HIGH);
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_06_PIN_07, BSP_IO_LEVEL_HIGH);
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_06_PIN_11, BSP_IO_LEVEL_HIGH);
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_06_PIN_12, BSP_IO_LEVEL_HIGH);
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_06_PIN_13, BSP_IO_LEVEL_HIGH);
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_06_PIN_14, BSP_IO_LEVEL_HIGH);
}
void LED_Initial_Setting()
{
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_10_PIN_08, BSP_IO_LEVEL_HIGH); // LED 1 OFF
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_10_PIN_09, BSP_IO_LEVEL_HIGH); // LED 2 OFF
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_10_PIN_10, BSP_IO_LEVEL_HIGH); // LED 3 OFF
    R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_11_PIN_00, BSP_IO_LEVEL_HIGH); // LED 4 OFF
}
void R_AGT0_Interrupt(timer_callback_args_t *p_args)
{
    FSP_PARAMETER_NOT_USED(p_args);
    LED_Initial_Setting();
    led_select++;
    R_IOPORT_PinWrite(&g_ioport_ctrl, led_index[(led_select - 1) % 4], BSP_IO_LEVEL_LOW);
    if ((led_select - 1) % 4 == 0)
        count_number++;
}
void R_IRQ11_Interrupt(external_irq_callback_args_t *p_args)
{
    FSP_PARAMETER_NOT_USED(p_args);
    stop_key =! stop_key;
}
/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
